import { Link } from "@/i18n/navigation";
import { Archive, ArrowLeft } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Deep Personality",
  description:
    "Read the Terms of Service for Deep Personality, the AI-powered personality assessment platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 w-full border-b border-border/60 bg-background/80 backdrop-blur-lg">
        <div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-4 lg:px-8">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary">
              <Archive className="h-5 w-5 text-primary-foreground" />
            </div>
            <span className="text-lg font-bold tracking-tight text-foreground font-serif">
              Deep Personality
            </span>
          </Link>
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Home
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="mx-auto max-w-4xl px-4 py-12 lg:px-8 lg:py-16">
        <h1 className="text-3xl font-extrabold text-foreground font-serif lg:text-4xl mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground mb-10">
          Last updated: February 5, 2026
        </p>

        <div className="prose-legal space-y-8 text-foreground text-sm leading-relaxed">
          {/* 1 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              1. Acceptance of Terms
            </h2>
            <p className="text-muted-foreground">
              By accessing and using Deep Personality (&ldquo;the App&rdquo;), you agree to
              be bound by these Terms of Service. If you do not agree with any
              part of these terms, please do not use the App.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              2. Educational and Informational Purpose
            </h2>
            <p className="text-xs font-semibold uppercase tracking-wider text-primary mb-2">
              Consumer Information Product
            </p>
            <p className="text-muted-foreground mb-3">
              This service provides educational and informational content about
              personality psychology. It is not a psychological service,
              psychological assessment, or psychological treatment as defined by
              any regulatory body.
            </p>
            <p className="text-muted-foreground mb-3">
              Deep Personality is a consumer information product, similar to:
            </p>
            <ul className="list-disc pl-6 space-y-1 text-muted-foreground mb-3">
              <li>Genetic ancestry services (23andMe, Ancestry)</li>
              <li>Personality type indicators (16Personalities, Enneagram tests)</li>
              <li>Health tracking applications (fitness trackers, sleep monitors)</li>
            </ul>
            <p className="text-muted-foreground">
              Like these services, we provide data and interpretations for
              personal use. We do not provide clinical diagnosis, treatment
              recommendations, or professional psychological services.
            </p>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              3. No Professional Relationship
            </h2>
            <p className="text-muted-foreground mb-3">
              Use of this service does not create a psychologist-patient,
              therapist-client, or any professional healthcare relationship. Deep
              Personality Inc. does not employ, contract with, or represent any
              licensed psychologists, psychiatrists, or mental health
              professionals in providing this service.
            </p>
            <p className="text-muted-foreground">
              The interpretations provided are generated by artificial
              intelligence algorithms and have not been reviewed, approved, or
              endorsed by any licensed mental health professional or regulatory
              body.
            </p>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              4. Nature of the Service
            </h2>
            <p className="text-xs font-semibold uppercase tracking-wider text-primary mb-2">
              Important Disclaimer
            </p>
            <p className="text-muted-foreground mb-3">
              Deep Personality provides personality insights and self-reflection
              tools based on established psychological frameworks. The
              assessments include personality traits, Dark Triad indicators, and
              mental health screening questions (GAD-7, PHQ-9, ACE, PCL-5).
            </p>
            <p className="text-muted-foreground mb-2 font-semibold">
              This App is NOT:
            </p>
            <ul className="list-disc pl-6 space-y-1 text-muted-foreground mb-3">
              <li>Medical or psychological advice</li>
              <li>A diagnostic tool for mental health conditions</li>
              <li>A substitute for professional mental health care</li>
              <li>A replacement for consultation with qualified healthcare providers</li>
            </ul>
            <p className="text-muted-foreground">
              All scores and analyses are based on self-reported responses and
              should be used for personal reflection purposes only. If you are
              experiencing mental health concerns, please consult a licensed
              mental health professional.
            </p>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              5. Dark Triad Assessment
            </h2>
            <p className="text-muted-foreground mb-3">
              The Dark Triad assessment measures three personality traits:
              Narcissism, Machiavellianism, and Psychopathy. These are
              personality dimensions that exist on a spectrum in the general
              population.
            </p>
            <p className="text-muted-foreground">
              High scores do not indicate a personality disorder or mental
              illness. These traits are not clinical diagnoses and should not be
              interpreted as such. The results are intended for self-awareness
              and personal development only.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              6. Mental Health Screening Tools
            </h2>
            <p className="text-muted-foreground mb-3">
              The App includes validated screening instruments (GAD-7, PHQ-9,
              ACE, PCL-5) that are commonly used in clinical settings. However,
              their use in this App is for informational purposes only.
            </p>
            <p className="text-muted-foreground mb-3">
              If your results suggest elevated anxiety, depression, trauma, or
              other concerns, please seek support from a qualified mental health
              professional.
            </p>
            <p className="text-muted-foreground font-semibold">
              Crisis Resources: If you are in crisis or having thoughts of
              self-harm, please contact your local emergency services or a crisis
              helpline immediately.
            </p>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              7. User Responsibility
            </h2>
            <p className="text-muted-foreground mb-2">
              You acknowledge and agree that:
            </p>
            <ul className="list-disc pl-6 space-y-1 text-muted-foreground">
              <li>You are using this App voluntarily and at your own discretion</li>
              <li>You are solely responsible for how you interpret and act upon your results</li>
              <li>You will not use the results to diagnose yourself or others</li>
              <li>You will seek professional help for any mental health concerns</li>
              <li>Sharing your profile with others is your choice and responsibility</li>
            </ul>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              8. AI-Generated Content Limitations
            </h2>
            <p className="text-muted-foreground mb-2">
              The App uses artificial intelligence to generate personality
              analyses and relationship insights. Our AI interpretations are:
            </p>
            <ul className="list-disc pl-6 space-y-1 text-muted-foreground mb-3">
              <li>Generated by language models trained on general psychological literature</li>
              <li>Not validated against clinical diagnostic standards</li>
              <li>Not equivalent to assessment by a licensed professional</li>
              <li>Provided &ldquo;as-is&rdquo; without guarantee of accuracy or applicability</li>
            </ul>
            <p className="text-muted-foreground">
              Different users with identical scores may receive different
              interpretations. The AI does not have access to your life context,
              history, or circumstances that a professional would consider.
              AI-generated content should not be relied upon for important
              decisions.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              9. Assumption of Risk
            </h2>
            <p className="text-muted-foreground mb-2">
              By using this service, you acknowledge and accept that:
            </p>
            <ul className="list-disc pl-6 space-y-1 text-muted-foreground mb-3">
              <li>Personality assessment involves inherent uncertainty</li>
              <li>Self-report data has known limitations</li>
              <li>You may encounter information about yourself that is uncomfortable</li>
              <li>Psychological self-reflection can occasionally trigger emotional responses</li>
              <li>You are solely responsible for how you interpret and use results</li>
            </ul>
            <p className="text-muted-foreground">
              You voluntarily assume all risks associated with using this
              service.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              10. Limitation of Liability
            </h2>
            <p className="text-muted-foreground">
              To the maximum extent permitted by law, Deep Personality Inc. and
              its operators shall not be liable for any direct, indirect,
              incidental, consequential, or punitive damages arising from your
              use of the App, including but not limited to emotional distress,
              relationship decisions, or actions taken based on assessment
              results.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              11. Indemnification
            </h2>
            <p className="text-muted-foreground mb-2">
              You agree to indemnify, defend, and hold harmless Deep Personality
              Inc., its officers, directors, employees, and agents from any
              claims, damages, losses, or expenses (including reasonable legal
              fees) arising from:
            </p>
            <ul className="list-disc pl-6 space-y-1 text-muted-foreground">
              <li>Your use of the service</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of any third party rights</li>
              <li>Any claim that your use of results caused harm to yourself or others</li>
            </ul>
          </section>

          {/* 12 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              12. Privacy
            </h2>
            <p className="text-muted-foreground">
              Your use of the App is also governed by our{" "}
              <Link href="/privacy" className="text-primary underline underline-offset-2 hover:opacity-80">
                Privacy Policy
              </Link>
              , which describes how we collect, use, and protect your personal
              information.
            </p>
          </section>

          {/* 13 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              13. Modifications
            </h2>
            <p className="text-muted-foreground">
              We reserve the right to modify these Terms of Service at any time.
              Continued use of the App after changes constitutes acceptance of
              the modified terms.
            </p>
          </section>

          {/* 14 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              14. Geographic Availability
            </h2>
            <p className="text-muted-foreground mb-3">
              This service is available to users in Canada and the United States
              only. By using this service, you represent that you are located in
              one of these countries.
            </p>
            <p className="text-muted-foreground mb-3">
              <strong>European Union Notice:</strong> This service is not
              available to residents of the European Union, European Economic
              Area, or United Kingdom. We use IP-based geo-blocking to enforce
              this restriction.
            </p>
            <p className="text-muted-foreground">
              <strong>VPN and Circumvention:</strong> If you are a resident of a
              restricted region and attempt to access this service using a VPN,
              proxy, or other means to circumvent our geo-blocking, you are in
              violation of these Terms of Service. Any such unauthorized access
              may result in immediate account termination and deletion of your
              data without notice or refund.
            </p>
          </section>

          {/* 15 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              15. Dispute Resolution
            </h2>
            <p className="text-xs font-semibold uppercase tracking-wider text-primary mb-2">
              Arbitration Agreement — Please Read Carefully
            </p>
            <p className="text-muted-foreground mb-3">
              Any dispute, controversy, or claim arising out of or relating to
              this service shall be resolved through binding arbitration in
              Vancouver, British Columbia, Canada, administered by the British
              Columbia International Commercial Arbitration Centre (BCICAC) in
              accordance with its rules, rather than in court. Judgment on the
              award may be entered in any court having jurisdiction.
            </p>
            <p className="text-muted-foreground mb-3">
              For users in the United States: By using this service, you agree
              that the Federal Arbitration Act governs the interpretation and
              enforcement of this arbitration provision, and you waive your right
              to a jury trial.
            </p>
            <p className="text-muted-foreground mb-3">
              <strong>Class Action Waiver:</strong> You agree to waive any right
              to participate in class action lawsuits, class-wide arbitration, or
              any consolidated or representative proceedings against Deep
              Personality Inc. All claims must be brought in your individual
              capacity.
            </p>
            <p className="text-muted-foreground mb-3">
              <strong>Exceptions:</strong> This arbitration agreement does not
              apply to: (a) disputes that qualify for small claims court in your
              jurisdiction; (b) claims for injunctive relief to prevent
              unauthorized use of intellectual property; or (c) complaints filed
              with government agencies (such as the FTC or privacy
              commissioners) that may seek relief on your behalf.
            </p>
            <p className="text-muted-foreground">
              <strong>Costs:</strong> Each party shall bear its own costs and
              attorney fees. If any portion of this arbitration clause is found
              unenforceable, the remaining portions shall remain in effect.
            </p>
          </section>

          {/* 16 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              16. Governing Law
            </h2>
            <p className="text-muted-foreground">
              These Terms of Service are governed by the laws of British
              Columbia, Canada, without regard to conflict of law principles. For
              users in the United States, the Federal Arbitration Act governs
              arbitration-related matters.
            </p>
          </section>

          {/* 17 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              17. Severability
            </h2>
            <p className="text-muted-foreground">
              If any provision of these Terms is found to be invalid, illegal, or
              unenforceable by a court of competent jurisdiction, such invalidity
              shall not affect the validity of the remaining provisions, which
              shall remain in full force and effect. The invalid provision shall
              be modified to the minimum extent necessary to make it valid and
              enforceable while preserving the parties&apos; original intent.
            </p>
          </section>

          {/* 18 */}
          <section>
            <h2 className="text-lg font-bold font-serif text-foreground mb-3">
              18. Contact
            </h2>
            <p className="text-muted-foreground">
              If you have questions about these Terms of Service, please contact
              us at{" "}
              <a
                href="mailto:support@deeppersonality.app"
                className="text-primary underline underline-offset-2 hover:opacity-80"
              >
                support@deeppersonality.app
              </a>
              .
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border/60 bg-card">
        <div className="mx-auto max-w-4xl px-4 py-8 lg:px-8 flex flex-col items-center justify-between gap-4 sm:flex-row">
          <p className="text-xs text-muted-foreground">
            2024-2026 Deep Personality Inc. All rights reserved.
          </p>
          <div className="flex items-center gap-6">
            <Link
              href="/terms"
              className="text-xs font-medium text-foreground"
            >
              Terms of Service
            </Link>
            <Link
              href="/privacy"
              className="text-xs text-muted-foreground transition-colors hover:text-foreground"
            >
              Privacy Policy
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
