import type { LifePathContent } from "../types";

export const PATH_11: LifePathContent = {
  pathNumber: 11,
  name: "The Intuitive",
  shortName: "Intuitive",
  tagline: "Visionary, electrically sensitive, and born to channel light that most people can only glimpse",
  color: "#7B6B8A",
  heroImage: "/characters/numerology/path11/path11-reveal.svg",
  sectionImages: {
    strengths: "/characters/numerology/path11/path11-strengths.svg",
    relationships: "/characters/numerology/path11/path11-relationships.svg",
    career: "/characters/numerology/path11/path11-career.svg",
    growth: "/characters/numerology/path11/path11-growth.svg",
  },

  overview: `Life Path 11 is a master number — and in numerology, that word is not honorary. It is a voltage warning. You carry the sensitivity and relational attunement of the 2, but amplified to a frequency that is no longer merely personal. Where the 2 feels what is happening in the room, the 11 feels what is happening beneath the room, behind it, and several rooms ahead. You arrived wired to a signal that most people cannot detect: the hum of what wants to emerge, the tremor before the earthquake, the meaning that has not yet found its words. This is not metaphor. You have likely spent your life knowing things you could not explain, sensing shifts before they register on anyone else's instruments, and carrying an inner intensity that the world alternately reveres and pathologises.

The cost of this wiring is real and relentless. The master number 11 does not simply add spiritual sensitivity on top of an ordinary nervous system — it rewrites the nervous system entirely. You feel everything at higher amplitude: joy is ecstatic, grief is annihilating, crowds are storms, silence is sanctuary. Your body absorbs the emotional weather of every environment you enter, often before you have consciously registered the door. This makes you extraordinarily perceptive and extraordinarily exhausted in almost equal measure. The world was not designed for your bandwidth, and until you learn to manage the signal-to-noise ratio, you may oscillate between periods of breathtaking inspiration and periods of crushing overwhelm — sometimes within the same afternoon.

What redeems this intensity is purpose. The 11 is the spiritual messenger of the numerological system — the lightning rod through which insight, inspiration, and illumination travel from the unseen into the manifest. You are not here to live a quiet, comfortable life. You are here to receive something and transmit it: a vision, a healing, a body of work, a way of seeing that the collective needs but cannot access without a translator. When you align with this purpose, the same sensitivity that once felt like a curse reveals itself as the instrument it always was. The challenge of the master number is that it demands you integrate the extraordinary with the ordinary — to be the vessel without shattering, to carry the voltage without burning out, to walk between worlds without losing your footing in either one.`,

  coreEnergies: [
    { name: "Intuition", score: 95, description: "A knowing that arrives before thought — not a hunch but a direct perception of what lies beneath surfaces, behind words, and ahead of visible events" },
    { name: "Spiritual Sensitivity", score: 90, description: "An innate attunement to the numinous, the energetic, and the archetypal — you register frequencies that most people experience only in dreams or crisis" },
    { name: "Inspirational Power", score: 85, description: "A capacity to transmit vision that moves others at the level of soul — your words, your presence, your creative output carry a charge that awakens something dormant" },
    { name: "Nervous System Intensity", score: 80, description: "A heightened physiological sensitivity that makes you a precision instrument for perception — and equally vulnerable to overstimulation and energetic overload" },
    { name: "Groundedness", score: 25, description: "A lower instinct for the practical, the mundane, and the embodied — the very quality you must cultivate most deliberately to sustain the gifts the other energies provide" },
  ],

  strengths: [
    {
      title: "Luminous Intuition",
      description: "Your knowing does not follow the ordinary route of observation, analysis, and conclusion — it arrives whole, often before the evidence does, as though you are reading from a manuscript the rest of the world has not yet received.",
      deepDive: `The intuition of the 11 is qualitatively different from the gut feelings that everyone occasionally experiences. It is not a vague sense that something is off — it is a direct download, a sudden and complete knowing that bypasses the rational mind entirely. You may walk into a meeting and know immediately which partnership will fail. You may meet someone and feel the shape of their grief before they have spoken a word. You may wake at three in the morning with a creative solution so fully formed that it feels dictated rather than invented. This capacity is your primary gift, and it is also the source of your deepest frustration, because the world runs on evidence and you traffic in a currency that precedes it. You have likely spent years doubting your own perceptions — not because they were wrong, but because you could not prove them through channels the rational world respects. The most evolved 11s learn to trust the signal without needing external validation, while developing enough discernment to distinguish genuine intuition from the projections of anxiety or desire. The difference is texture: true intuitive knowing arrives with a quality of calm certainty, even when its content is uncomfortable. Fear-based projection arrives with urgency and emotional charge. Learning to feel this distinction in your own body is the central discipline of your life.`,
    },
    {
      title: "Inspirational Transmission",
      description: "You do not merely communicate ideas — you transmit states. Something in your presence, your voice, or your creative expression reaches past the intellect and touches the part of people that remembers what it came here to do.",
      deepDive: `The 11 is the channel number — the frequency through which higher inspiration enters the collective. This does not require you to stand on a stage or lead a movement, though some 11s do. It means that when you are aligned and clear, your very presence becomes catalytic. People feel something shift when they are near you: a permission to feel more deeply, to speak more honestly, to remember the larger story their daily routine has caused them to forget. This transmission happens through whatever medium you inhabit — conversation, art, writing, healing work, teaching, even silence. You have likely noticed that people tell you things they do not tell anyone else, or that a room changes temperature when you walk in, or that your creative work touches people in ways that seem disproportionate to what you consciously intended. This is the 11's inspirational power at work. The shadow is that this capacity can become performative — the 11 who has learned that they carry a charge can begin to manipulate it, using spiritual charisma as a form of control or identity rather than service. The practice is staying humble before the gift, remembering that you are the instrument and not the composer, and ensuring that the light you transmit has passed through your own honest reckoning before you offer it to others.`,
    },
    {
      title: "Emotional Clairvoyance",
      description: "You read the emotional landscape of individuals and groups with an accuracy that borders on the uncanny — sensing not only what people feel, but what they have not yet allowed themselves to feel.",
      deepDive: `The 2 energy at the root of the 11 gives you an extraordinary emotional intelligence, and the master number amplification lifts it from empathy into something closer to clairvoyance. You do not merely pick up on moods — you perceive the entire emotional architecture of a person or a room: what is being expressed, what is being suppressed, what is about to surface, and what has been buried so long that its owner has forgotten it is there. In therapeutic, healing, or creative work, this makes you devastatingly effective. You know exactly where the wound is before the client has located it themselves. You sense the unspoken tension in a team before it erupts. You feel the precise moment when someone's composure is a performance and their real feeling is pressing against the walls. The danger is twofold. First, this perception can be overwhelming — you absorb emotional information constantly and often involuntarily, which means you need significantly more recovery time than others. Second, you may struggle to distinguish between what you perceive and what you project: the line between reading someone's pain and imagining it can blur when your antenna is always on. The discipline is learning to observe without absorbing, to perceive without carrying, and to trust your emotional clairvoyance while maintaining the humility to verify it before acting on it.`,
    },
  ],

  growthEdges: [
    {
      title: "Anxiety and Overwhelm",
      teaser: "Your nervous system is tuned to a frequency the world was not built for — and without deliberate management, the signal becomes unbearable.",
      fullExplanation: `The master number 11 bestows extraordinary perception, but it does so by running a higher voltage through a human nervous system that was designed for ordinary current. The result is a lifelong susceptibility to anxiety, sensory overwhelm, and what can feel like a fundamental inability to cope with the pace and noise of modern life. You may have been diagnosed with anxiety, high sensitivity, or a sensory processing difference — and while these labels may be clinically accurate, they miss the deeper truth: your system is not malfunctioning. It is functioning at a level that the standard-issue human life does not accommodate. Crowds drain you. Conflict electrifies you. Transitions that others navigate smoothly can leave you vibrating for hours. The cumulative effect is a pattern of expansion and collapse: periods of extraordinary creative output or spiritual insight followed by crashes into exhaustion, withdrawal, or illness. The growth edge is not to dampen the signal — you cannot, and attempting to do so through numbing behaviours only postpones the crash. It is to become masterful at regulating your exposure, building recovery into your daily architecture, and accepting that your nervous system has non-negotiable requirements that you must honour with the same seriousness you would give a medical condition. The 11 who learns to protect their instrument without resenting its demands becomes capable of sustaining the very gifts that once felt like afflictions.`,
      premiumHook: "Your premium report identifies your specific overwhelm triggers and maps a personalised nervous system management protocol calibrated to the intensity of your 11 energy.",
    },
    {
      title: "Difficulty Staying Grounded",
      teaser: "You live so naturally in the realm of vision, energy, and intuitive perception that the practical world can feel like a foreign language you were never taught.",
      fullExplanation: `The 11's gifts are transpersonal — they orient you upward and inward, toward inspiration, spiritual insight, and subtle perception. The cost is that the downward, outward motion of daily life — bills, logistics, physical maintenance, the relentless mundanity of being a body in a material world — can feel almost unbearably tedious or genuinely confusing. You may struggle with time management, financial organisation, domestic upkeep, or the practical steps required to bring a vision into physical form. You are magnificent at receiving the blueprint but often lost when it comes to pouring the foundation. This is the classic master number paradox: the 11 can see the cathedral in perfect detail but cannot remember where they left their keys. The world may read this as irresponsibility or immaturity, and you may internalise that judgment, creating a painful gap between your spiritual capacities and your practical self-esteem. The growth edge is understanding that grounding is not a compromise of your gifts — it is the precondition for their sustainable expression. The most powerful 11s are those who have built a disciplined, embodied container for their visionary energy: a physical routine, a financial structure, a domestic order that keeps the channel clear. Without ground, lightning has nowhere to go. It simply destroys whatever it strikes.`,
      premiumHook: "Discover the specific grounding practices, daily structures, and embodiment techniques that anchor your 11 energy without dulling its edge.",
    },
    {
      title: "Imposter Syndrome Around Spiritual Gifts",
      teaser: "You sense that you carry something rare — and spend half your life convinced you are making it up.",
      fullExplanation: `Perhaps the cruelest irony of the 11 vibration is that the same sensitivity that gives you access to extraordinary perception also gives you access to extraordinary doubt. You know things, feel things, and see things that others do not — but because the dominant culture offers no framework for validating these experiences, you oscillate between moments of profound trust in your gifts and long stretches of believing you have fabricated everything. This is not ordinary self-doubt; it is a fundamental uncertainty about the nature of your own inner experience. Did you really sense that person's grief, or did you project it? Was that creative vision genuinely inspired, or are you just grandiose? Are you a channel, or are you delusional? The imposter syndrome of the 11 is amplified by the fact that the word "master" sits in front of your number — suggesting a spiritual authority you may feel entirely unready to claim. The growth edge is recognising that this doubt is itself part of the master number's initiation. The 11 is not asked to be certain; it is asked to act in the presence of uncertainty, to trust the knowing even when it cannot be proven, and to offer the gift even when the inner critic insists it is worthless. Every master number carries the option of living as its base number — in your case, the 2 — and the temptation to retreat from the 11's demands into the 2's relative safety is constant. The work is choosing, again and again, to live at the voltage you were built for.`,
      premiumHook: "Your premium report maps the specific doubt patterns that undermine your 11 expression and provides a framework for distinguishing genuine discernment from fear-based self-sabotage.",
    },
  ],

  relationships: `In relationships, you bring a depth of presence that is almost supernatural. You feel your partner before they speak — their mood, their unspoken need, the shift in their energy that signals something has changed. This makes you an extraordinarily attentive lover, capable of a tenderness and emotional precision that most people have never experienced. When you turn the full beam of your attention toward someone, they feel held at a level that goes beyond words. The 11 in love is the candlelit room, the gaze that sees everything, the hand that reaches out at exactly the right moment.

The shadow side of this intensity is that it can overwhelm both you and your partner. You may absorb their emotions so completely that you lose track of your own. You may project your intuitive perceptions onto them — telling them what they feel before they have had the chance to discover it themselves. And you may carry an unspoken expectation that the relationship should operate at the same spiritual altitude you inhabit, which can leave more grounded partners feeling inadequate or perpetually misunderstood. Your nervous system's reactivity means that conflict does not simply upset you — it devastates you, and you may avoid necessary confrontations to protect your own equilibrium, allowing resentment to accumulate in the spaces where honesty should live.

The healthiest 11 relationships are those with partners who are emotionally secure, spiritually curious, and strong enough to hold their own centre in the presence of your intensity. You need someone who honours your sensitivity without tiptoeing around it — who can sit with you in the deep water without panicking, but who also insists on coming up for air. Equally vital is a partner who grounds you: someone with enough practical solidity to anchor the relationship in the real world while you navigate the unseen one. The 11 who finds this balance discovers that intimacy is not a threat to their sensitivity but the crucible in which their gifts are most profoundly refined.`,

  compatibilityNotes: {
    2: "The 2 shares your root energy but at a gentler frequency — they understand your sensitivity intuitively and offer a steadiness that can feel like coming home. The risk is mutual over-accommodation, where neither partner names what they actually need.",
    4: "The 4's earthy discipline is medicine for your ungrounded brilliance. They build the container your visions require, and you remind them that life has dimensions their spreadsheets cannot capture. A pairing of sky and soil.",
    6: "The 6's devotion and domestic warmth create a nest where your sensitive system can truly rest. They offer the unconditional holding you secretly crave, while your depth prevents their nurturing from becoming mere routine.",
    7: "Two of the most spiritually attuned numbers in the system. Together you create a relationship of extraordinary inner richness — shared silence that speaks, intuitive exchanges that bypass language entirely. Guard against losing the practical world.",
    9: "The 9's universal compassion meets your transpersonal sensitivity in a relationship that can feel like a shared mission. Both of you sense the larger currents, and together you can channel something genuinely healing — if you remember to tend to each other, not just the world.",
    11: "Two master number 11s together is an experience of almost unbearable recognition — the relief of being fully seen by someone who operates at your frequency. The danger is amplified instability: two highly sensitive systems without a grounding force between them.",
  },

  careerPaths: `You thrive in roles where your intuitive gifts are not merely tolerated but actively required — where the work demands the kind of perception that cannot be taught in a training manual. Your ideal career is one that positions you as a conduit between the unseen and the expressed: translating subtle information into forms that others can receive, whether through words, art, healing, or visionary leadership.

Strong career directions include: psychotherapy and counselling, energy healing and bodywork, spiritual teaching and guidance, the arts — particularly music, poetry, and visually evocative work — writing that illuminates the inner life, channel work and mediumship, visionary leadership in organisations aligned with purpose, inspirational speaking, dream work and depth psychology, and any role where your capacity to sense what is emerging gives you an advantage others cannot replicate.

You tend to struggle in highly competitive, purely analytical, or emotionally sterile environments. Corporate cultures that reward political manoeuvring over genuine insight will drain you at a cellular level, and roles that require you to suppress your sensitivity in favour of detached efficiency will slowly erode both your health and your gifts. The key is finding work that honours the full spectrum of your wiring — your need for meaning, your sensitivity to environment, and your capacity to perceive what others cannot — while providing enough structure and financial stability to keep your feet on the ground.`,

  workStyle: `You work in cycles of inspiration and integration — bursts of extraordinary creative or intuitive output followed by periods where you must retreat, process, and restore. Attempting to maintain a constant, steady-state productivity is not merely ineffective for you; it is destructive. Your best work arrives like weather: you cannot schedule it, but you can learn to recognise the conditions that invite it and build a life that accommodates its rhythm.

When the inspiration is flowing, you are capable of work that carries a quality others cannot quite name — a luminosity, a depth of feeling, a precision of insight that seems to come from somewhere beyond ordinary effort. Colleagues may describe your contributions as visionary or uncannily perceptive. When the inspiration recedes, you may feel hollow, fraudulent, or creatively barren, and the temptation to force productivity during these fallow periods must be resisted. The integration phase is not laziness; it is the underground work of the next emergence. Your ideal work environment is quiet, aesthetically nourishing, and free from the energetic chaos of open-plan offices and constant interruption.`,

  spiritualTheme: `The spiritual lesson of Life Path 11 is learning to be a clear channel — to receive the light without distorting it through ego, and to transmit it without being consumed by its intensity. You are wired for revelation, but revelation is not a comfortable experience. It demands that you surrender the part of yourself that wants to control the message, that wants credit for the insight, that wants to be seen as special rather than simply useful. The master number asks you to hold a paradox: you carry something extraordinary, and you must not identify with it. The moment you confuse the gift with your identity, the channel narrows and the transmission distorts. Your deepest spiritual work is becoming transparent — so aligned with your own truth that the inspiration passes through you cleanly, like light through clear glass.

Many 11s experience a defining spiritual crisis — a period of breakdown that is actually breakthrough, where the old identity collapses under the weight of the energy it was never designed to carry. This is not failure; it is the master number's initiation. The 2 that lives inside the 11 wants safety, partnership, and belonging. The 11 demands that these desires be placed in service of something transpersonal. The integration point is not choosing one over the other — it is learning to be fully human and fully attuned to the extraordinary at the same time. The 11 who survives this passage emerges not as a guru or a saint but as something rarer: a person who can walk into a room full of suffering and, without saying a word, remind everyone in it that there is more to the story than what they can see. That is the master number's promise, and it is worth every volt it costs you.`,

  lifeLessons: [
    "Trust the signal — learning to honour your intuitive knowing even when the evidence has not yet arrived and the world insists on proof you cannot provide",
    "Protect the instrument — understanding that your sensitivity is not a flaw to be corrected but a precision tool that requires deliberate maintenance, rest, and sacred boundaries",
    "Ground the vision — discovering that inspiration without embodiment is hallucination, and that your gifts become real only when you anchor them in discipline, structure, and physical form",
    "Surrender the identity — recognising that you are the channel and not the source, and that the spiritual power you carry serves best when your ego steps aside",
    "Integrate the ordinary — accepting that the master number's highest expression is not transcendence but incarnation: learning to carry the extraordinary into the kitchen, the commute, and the Tuesday afternoon",
  ],

  toolkit: [
    {
      title: "The Voltage Check",
      context: "Your nervous system operates at a frequency that requires active monitoring. Without regular check-ins, you will not notice overload until the crash — and by then, recovery takes days instead of minutes.",
      action: "Three times daily — morning, midday, and evening — pause for sixty seconds and rate your internal voltage on a scale of one to ten. One is depleted; ten is overwhelmed. If you are above seven, immediately reduce stimulation: leave the room, cancel the next non-essential engagement, put your phone in another room, or lie on the floor with your eyes closed. If you are below three, you have been giving without receiving and need nourishment — not productivity. Keep a simple log. Within weeks, you will begin to recognise the early warning signs that currently escape your notice, and your crashes will become less frequent and less severe.",
    },
    {
      title: "The Grounding Anchor",
      context: "Your energy naturally rises — toward vision, intuition, and the transpersonal. Without a deliberate downward practice, you become brilliant but brittle, inspired but unstable.",
      action: "Each morning before engaging with any screen or conversation, spend five minutes in physical contact with something solid: bare feet on the floor, hands on a stone, your back against a wall. As you breathe, direct your attention downward — from the crown of your head through your chest, your belly, your legs, into whatever surface supports you. With each exhale, silently name one concrete, physical thing you are grateful for: the temperature of the air, the texture of the sheet, the taste of water. This practice is not symbolic; it is neurological. You are training your system to include the body in your field of awareness rather than operating exclusively from the upper registers where the 11 energy naturally lives.",
    },
    {
      title: "The Channel Clearing",
      context: "Your gift depends on clarity — and clarity depends on regular release of the emotional, energetic, and psychic residue that accumulates when you live at your frequency.",
      action: "Once weekly, set aside thirty minutes in a private space. Begin by writing rapidly and without censorship everything that is currently circulating in your system: anxieties, intuitions, images, fragments of other people's emotions, unfinished creative impulses, unnamed dread. Do not organise or interpret. When the flow stops, read what you have written once, then destroy the paper. Follow this with ten minutes of silence — not meditation with a technique, but simple, unstructured quiet. You are allowing the channel to empty completely so that what flows through next is current rather than residue. Over time, this practice sharpens your intuitive accuracy dramatically, because the signal is no longer competing with accumulated noise.",
    },
  ],

  descriptionInsight: "Life Path 11 — the master number who walks between worlds, learning to channel the extraordinary through a human life without losing their footing in either realm.",
};
